# Basic Information 
title: Yuying LONG
position: Ph. D. student
affiliation: The Hong Kong Polytechnic University
email: yuying.long@connect.polyu.hk

# Search Engine Optimization (SEO)
keywords: yuying long, long yuying, yuyinglong, longyuying

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: text #text/icon
google_scholar: https://scholar.google.com/citations?user=1MRupSUAAAAJ&hl=zh-CN

# Images 
avatar: ./assets/img/LONG_Yuying.jpg
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
